/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutStats { 'clientsCount' : string, 'experience' : string }
export interface BillingItem {
  'id' : bigint,
  'purchasePrice' : bigint,
  'name' : string,
  'sellingPrice' : bigint,
  'category' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'isRead' : boolean,
  'message' : string,
  'phone' : string,
}
export interface CustomerOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'serviceName' : string,
  'date' : string,
  'notes' : string,
  'quantity' : bigint,
  'serviceId' : string,
  'phone' : string,
  'totalPrice' : bigint,
}
export interface Employee {
  'id' : bigint,
  'age' : bigint,
  'cnic' : string,
  'designation' : string,
  'fullName' : string,
  'fatherName' : string,
  'bloodGroup' : string,
  'mobile' : string,
  'photo' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface Invoice {
  'id' : bigint,
  'customerName' : string,
  'balance' : bigint,
  'date' : string,
  'grandTotal' : bigint,
  'address' : string,
  'discount' : bigint,
  'phone' : string,
  'items' : Array<InvoiceItem>,
  'advance' : bigint,
}
export interface InvoiceItem {
  'total' : bigint,
  'billingItemId' : bigint,
  'quality' : string,
  'rate' : bigint,
  'srNo' : bigint,
  'particular' : string,
  'quantity' : string,
}
export interface Review {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'review' : string,
  'date' : string,
  'rating' : bigint,
}
export interface Service {
  'id' : bigint,
  'inStock' : boolean,
  'icon' : string,
  'name' : string,
  'description' : string,
  'discount' : bigint,
  'image' : ExternalBlob,
  'price' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBillingItem' : ActorMethod<[BillingItem], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addCustomerOrder' : ActorMethod<[CustomerOrder], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'addInvoice' : ActorMethod<[Invoice], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'deleteBillingItem' : ActorMethod<[bigint], boolean>,
  'deleteContactMessage' : ActorMethod<[bigint], boolean>,
  'deleteCustomerOrder' : ActorMethod<[bigint], boolean>,
  'deleteEmployee' : ActorMethod<[bigint], boolean>,
  'deleteInvoice' : ActorMethod<[bigint], boolean>,
  'deleteReview' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'getAboutStats' : ActorMethod<[], [] | [AboutStats]>,
  'getAdminPassword' : ActorMethod<[], string>,
  'getAllBillingItems' : ActorMethod<[], Array<BillingItem>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllCustomerOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getBillingItem' : ActorMethod<[bigint], [] | [BillingItem]>,
  'getContactMessage' : ActorMethod<[bigint], [] | [ContactMessage]>,
  'getCustomerOrder' : ActorMethod<[bigint], [] | [CustomerOrder]>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getLogo' : ActorMethod<[], string>,
  'getPendingReviews' : ActorMethod<[], Array<Review>>,
  'getReview' : ActorMethod<[bigint], [] | [Review]>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'markContactMessageRead' : ActorMethod<[bigint], boolean>,
  'setAboutStats' : ActorMethod<[AboutStats], undefined>,
  'setAdminPassword' : ActorMethod<[string], undefined>,
  'setLogo' : ActorMethod<[string], undefined>,
  'updateBillingItem' : ActorMethod<[bigint, BillingItem], boolean>,
  'updateCustomerOrder' : ActorMethod<[bigint, CustomerOrder], boolean>,
  'updateEmployee' : ActorMethod<[bigint, Employee], boolean>,
  'updateInvoice' : ActorMethod<[bigint, Invoice], boolean>,
  'updateReview' : ActorMethod<[bigint, Review], boolean>,
  'updateService' : ActorMethod<[bigint, Service], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];