/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BillingItem = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'category' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'serviceName' : IDL.Text,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'serviceId' : IDL.Text,
  'phone' : IDL.Text,
  'totalPrice' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'cnic' : IDL.Text,
  'designation' : IDL.Text,
  'fullName' : IDL.Text,
  'fatherName' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'mobile' : IDL.Text,
  'photo' : ExternalBlob,
});
export const InvoiceItem = IDL.Record({
  'total' : IDL.Nat,
  'billingItemId' : IDL.Nat,
  'quality' : IDL.Text,
  'rate' : IDL.Nat,
  'srNo' : IDL.Nat,
  'particular' : IDL.Text,
  'quantity' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'balance' : IDL.Nat,
  'date' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'address' : IDL.Text,
  'discount' : IDL.Nat,
  'phone' : IDL.Text,
  'items' : IDL.Vec(InvoiceItem),
  'advance' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'review' : IDL.Text,
  'date' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discount' : IDL.Nat,
  'image' : ExternalBlob,
  'price' : IDL.Text,
});
export const AboutStats = IDL.Record({
  'clientsCount' : IDL.Text,
  'experience' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBillingItem' : IDL.Func([BillingItem], [], []),
  'addContactMessage' : IDL.Func([ContactMessage], [], []),
  'addCustomerOrder' : IDL.Func([CustomerOrder], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'addInvoice' : IDL.Func([Invoice], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addService' : IDL.Func([Service], [], []),
  'deleteBillingItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomerOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAboutStats' : IDL.Func([], [IDL.Opt(AboutStats)], []),
  'getAdminPassword' : IDL.Func([], [IDL.Text], []),
  'getAllBillingItems' : IDL.Func([], [IDL.Vec(BillingItem)], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'getAllCustomerOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], []),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], []),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], []),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], []),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], []),
  'getBillingItem' : IDL.Func([IDL.Nat], [IDL.Opt(BillingItem)], []),
  'getContactMessage' : IDL.Func([IDL.Nat], [IDL.Opt(ContactMessage)], []),
  'getCustomerOrder' : IDL.Func([IDL.Nat], [IDL.Opt(CustomerOrder)], []),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], []),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], []),
  'getLogo' : IDL.Func([], [IDL.Text], []),
  'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], []),
  'getReview' : IDL.Func([IDL.Nat], [IDL.Opt(Review)], []),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], []),
  'markContactMessageRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'setAboutStats' : IDL.Func([AboutStats], [], []),
  'setAdminPassword' : IDL.Func([IDL.Text], [], []),
  'setLogo' : IDL.Func([IDL.Text], [], []),
  'updateBillingItem' : IDL.Func([IDL.Nat, BillingItem], [IDL.Bool], []),
  'updateCustomerOrder' : IDL.Func([IDL.Nat, CustomerOrder], [IDL.Bool], []),
  'updateEmployee' : IDL.Func([IDL.Nat, Employee], [IDL.Bool], []),
  'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [IDL.Bool], []),
  'updateReview' : IDL.Func([IDL.Nat, Review], [IDL.Bool], []),
  'updateService' : IDL.Func([IDL.Nat, Service], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BillingItem = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'serviceName' : IDL.Text,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'serviceId' : IDL.Text,
    'phone' : IDL.Text,
    'totalPrice' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'cnic' : IDL.Text,
    'designation' : IDL.Text,
    'fullName' : IDL.Text,
    'fatherName' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'mobile' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const InvoiceItem = IDL.Record({
    'total' : IDL.Nat,
    'billingItemId' : IDL.Nat,
    'quality' : IDL.Text,
    'rate' : IDL.Nat,
    'srNo' : IDL.Nat,
    'particular' : IDL.Text,
    'quantity' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'balance' : IDL.Nat,
    'date' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'address' : IDL.Text,
    'discount' : IDL.Nat,
    'phone' : IDL.Text,
    'items' : IDL.Vec(InvoiceItem),
    'advance' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'review' : IDL.Text,
    'date' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discount' : IDL.Nat,
    'image' : ExternalBlob,
    'price' : IDL.Text,
  });
  const AboutStats = IDL.Record({
    'clientsCount' : IDL.Text,
    'experience' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBillingItem' : IDL.Func([BillingItem], [], []),
    'addContactMessage' : IDL.Func([ContactMessage], [], []),
    'addCustomerOrder' : IDL.Func([CustomerOrder], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'addInvoice' : IDL.Func([Invoice], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addService' : IDL.Func([Service], [], []),
    'deleteBillingItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomerOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAboutStats' : IDL.Func([], [IDL.Opt(AboutStats)], []),
    'getAdminPassword' : IDL.Func([], [IDL.Text], []),
    'getAllBillingItems' : IDL.Func([], [IDL.Vec(BillingItem)], []),
    'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'getAllCustomerOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], []),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], []),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], []),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], []),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], []),
    'getBillingItem' : IDL.Func([IDL.Nat], [IDL.Opt(BillingItem)], []),
    'getContactMessage' : IDL.Func([IDL.Nat], [IDL.Opt(ContactMessage)], []),
    'getCustomerOrder' : IDL.Func([IDL.Nat], [IDL.Opt(CustomerOrder)], []),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], []),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], []),
    'getLogo' : IDL.Func([], [IDL.Text], []),
    'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], []),
    'getReview' : IDL.Func([IDL.Nat], [IDL.Opt(Review)], []),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], []),
    'markContactMessageRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'setAboutStats' : IDL.Func([AboutStats], [], []),
    'setAdminPassword' : IDL.Func([IDL.Text], [], []),
    'setLogo' : IDL.Func([IDL.Text], [], []),
    'updateBillingItem' : IDL.Func([IDL.Nat, BillingItem], [IDL.Bool], []),
    'updateCustomerOrder' : IDL.Func([IDL.Nat, CustomerOrder], [IDL.Bool], []),
    'updateEmployee' : IDL.Func([IDL.Nat, Employee], [IDL.Bool], []),
    'updateInvoice' : IDL.Func([IDL.Nat, Invoice], [IDL.Bool], []),
    'updateReview' : IDL.Func([IDL.Nat, Review], [IDL.Bool], []),
    'updateService' : IDL.Func([IDL.Nat, Service], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };