/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomerOrder {
    id: bigint;
    customerName: string;
    status: string;
    serviceName: string;
    date: string;
    notes: string;
    quantity: bigint;
    customerId?: bigint;
    serviceId: string;
    phone: string;
    totalPrice: bigint;
}
export interface InvoiceItem {
    total: bigint;
    billingItemId: bigint;
    quality: string;
    rate: bigint;
    srNo: bigint;
    particular: string;
    quantity: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: bigint;
    inStock: boolean;
    icon: string;
    name: string;
    description: string;
    discount: bigint;
    image: ExternalBlob;
    price: string;
}
export interface AboutStats {
    clientsCount: string;
    experience: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Invoice {
    id: bigint;
    customerName: string;
    balance: bigint;
    date: string;
    grandTotal: bigint;
    address: string;
    discount: bigint;
    phone: string;
    items: Array<InvoiceItem>;
    advance: bigint;
}
export interface BillingItem {
    id: bigint;
    purchasePrice: bigint;
    name: string;
    sellingPrice: bigint;
    category: string;
}
export interface ContactMessage {
    id: bigint;
    date: string;
    name: string;
    isRead: boolean;
    message: string;
    phone: string;
}
export interface SecurityAnswers {
    answer1: string;
    answer2: string;
    answer3: string;
}
export interface CustomerAccount {
    id: bigint;
    googleId: string;
    lastLoginAt: bigint;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    email: string;
    passwordHash: string;
    isGoogleUser: boolean;
    phone: string;
}
export interface Employee {
    id: bigint;
    age: bigint;
    cnic: string;
    designation: string;
    fullName: string;
    fatherName: string;
    bloodGroup: string;
    mobile: string;
    photo: ExternalBlob;
}
export interface Review {
    id: bigint;
    customerName: string;
    status: string;
    review: string;
    date: string;
    rating: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBillingItem(item: BillingItem): Promise<void>;
    addContactMessage(m: ContactMessage): Promise<void>;
    addCustomerOrder(o: CustomerOrder): Promise<void>;
    addEmployee(e: Employee): Promise<void>;
    addInvoice(inv: Invoice): Promise<void>;
    addReview(r: Review): Promise<void>;
    addService(s: Service): Promise<void>;
    deleteBillingItem(id: bigint): Promise<boolean>;
    deleteContactMessage(id: bigint): Promise<boolean>;
    deleteCustomer(id: bigint): Promise<boolean>;
    deleteCustomerOrder(id: bigint): Promise<boolean>;
    deleteEmployee(id: bigint): Promise<boolean>;
    deleteInvoice(id: bigint): Promise<boolean>;
    deleteReview(id: bigint): Promise<boolean>;
    deleteService(id: bigint): Promise<boolean>;
    getAboutStats(): Promise<AboutStats | null>;
    getAdminPassword(): Promise<string>;
    getAllBillingItems(): Promise<Array<BillingItem>>;
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAllCustomerOrders(): Promise<Array<CustomerOrder>>;
    getAllCustomers(): Promise<Array<CustomerAccount>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllReviews(): Promise<Array<Review>>;
    getAllServices(): Promise<Array<Service>>;
    getApprovedReviews(): Promise<Array<Review>>;
    getBillingItem(id: bigint): Promise<BillingItem | null>;
    getContactMessage(id: bigint): Promise<ContactMessage | null>;
    getCustomerByEmail(email: string): Promise<CustomerAccount | null>;
    getCustomerById(id: bigint): Promise<CustomerAccount>;
    getCustomerOrder(id: bigint): Promise<CustomerOrder | null>;
    getEmployee(id: bigint): Promise<Employee | null>;
    getInvoice(id: bigint): Promise<Invoice | null>;
    getInvoicesByCustomerPhone(phone: string): Promise<Array<Invoice>>;
    getLogo(): Promise<string>;
    getOrdersByCustomer(customerId: bigint): Promise<Array<CustomerOrder>>;
    getPendingReviews(): Promise<Array<Review>>;
    getReview(id: bigint): Promise<Review | null>;
    getSecurityAnswers(): Promise<SecurityAnswers>;
    getService(id: bigint): Promise<Service | null>;
    markContactMessageRead(id: bigint): Promise<boolean>;
    registerCustomer(c: CustomerAccount): Promise<void>;
    setAboutStats(stats: AboutStats): Promise<void>;
    setAdminPassword(v: string): Promise<void>;
    setLogo(v: string): Promise<void>;
    setSecurityAnswers(s: SecurityAnswers): Promise<void>;
    updateBillingItem(id: bigint, item: BillingItem): Promise<boolean>;
    updateCustomer(id: bigint, c: CustomerAccount): Promise<boolean>;
    updateCustomerLastLogin(id: bigint): Promise<void>;
    updateCustomerOrder(id: bigint, o: CustomerOrder): Promise<boolean>;
    updateEmployee(id: bigint, e: Employee): Promise<boolean>;
    updateInvoice(id: bigint, inv: Invoice): Promise<boolean>;
    updateReview(id: bigint, r: Review): Promise<boolean>;
    updateService(id: bigint, s: Service): Promise<boolean>;
}
import type { AboutStats as _AboutStats, BillingItem as _BillingItem, ContactMessage as _ContactMessage, CustomerAccount as _CustomerAccount, CustomerOrder as _CustomerOrder, Employee as _Employee, ExternalBlob as _ExternalBlob, Invoice as _Invoice, Review as _Review, Service as _Service, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBillingItem(arg0: BillingItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBillingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBillingItem(arg0);
            return result;
        }
    }
    async addContactMessage(arg0: ContactMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContactMessage(arg0);
            return result;
        }
    }
    async addCustomerOrder(arg0: CustomerOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomerOrder(to_candid_CustomerOrder_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomerOrder(to_candid_CustomerOrder_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(await to_candid_Employee_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(await to_candid_Employee_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoice(arg0);
            return result;
        }
    }
    async addReview(arg0: Review): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async addService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(await to_candid_Service_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(await to_candid_Service_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBillingItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBillingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBillingItem(arg0);
            return result;
        }
    }
    async deleteContactMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessage(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteCustomerOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomerOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomerOrder(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAboutStats(): Promise<AboutStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutStats();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutStats();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPassword(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPassword();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPassword();
            return result;
        }
    }
    async getAllBillingItems(): Promise<Array<BillingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBillingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBillingItems();
            return result;
        }
    }
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAllCustomerOrders(): Promise<Array<CustomerOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomerOrders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomerOrders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<CustomerAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return result;
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReviews();
            return result;
        }
    }
    async getBillingItem(arg0: bigint): Promise<BillingItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingItem(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingItem(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactMessage(arg0: bigint): Promise<ContactMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessage(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessage(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerByEmail(arg0: string): Promise<CustomerAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerByEmail(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerByEmail(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerById(arg0: bigint): Promise<CustomerAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerById(arg0);
            return result;
        }
    }
    async getCustomerOrder(arg0: bigint): Promise<CustomerOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrder(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrder(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: bigint): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByCustomerPhone(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByCustomerPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByCustomerPhone(arg0);
            return result;
        }
    }
    async getLogo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogo();
            return result;
        }
    }
    async getOrdersByCustomer(arg0: bigint): Promise<Array<CustomerOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomer(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomer(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingReviews();
            return result;
        }
    }
    async getReview(arg0: bigint): Promise<Review | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReview(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReview(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecurityAnswers(): Promise<SecurityAnswers> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityAnswers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityAnswers();
            return result;
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async markContactMessageRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactMessageRead(arg0);
            return result;
        }
    }
    async registerCustomer(arg0: CustomerAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0);
            return result;
        }
    }
    async setAboutStats(arg0: AboutStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAboutStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAboutStats(arg0);
            return result;
        }
    }
    async setAdminPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPassword(arg0);
            return result;
        }
    }
    async setLogo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLogo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLogo(arg0);
            return result;
        }
    }
    async setSecurityAnswers(arg0: SecurityAnswers): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSecurityAnswers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSecurityAnswers(arg0);
            return result;
        }
    }
    async updateBillingItem(arg0: bigint, arg1: BillingItem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBillingItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBillingItem(arg0, arg1);
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: CustomerAccount): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateCustomerLastLogin(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerLastLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerLastLogin(arg0);
            return result;
        }
    }
    async updateCustomerOrder(arg0: bigint, arg1: CustomerOrder): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerOrder(arg0, to_candid_CustomerOrder_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerOrder(arg0, to_candid_CustomerOrder_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEmployee(arg0: bigint, arg1: Employee): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, await to_candid_Employee_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, await to_candid_Employee_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: Invoice): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1);
            return result;
        }
    }
    async updateReview(arg0: bigint, arg1: Review): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReview(arg0, arg1);
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: Service): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, await to_candid_Service_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, await to_candid_Service_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CustomerOrder_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerOrder): CustomerOrder {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_Employee_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Promise<Employee> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Service_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Promise<Service> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AboutStats]): AboutStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BillingItem]): BillingItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactMessage]): ContactMessage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerAccount]): CustomerAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerOrder]): CustomerOrder | null {
    return value.length === 0 ? null : from_candid_CustomerOrder_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Promise<Employee | null> {
    return value.length === 0 ? null : await from_candid_Employee_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Review]): Review | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Promise<Service | null> {
    return value.length === 0 ? null : await from_candid_Service_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: string;
    serviceName: string;
    date: string;
    notes: string;
    quantity: bigint;
    customerId: [] | [bigint];
    serviceId: string;
    phone: string;
    totalPrice: bigint;
}): {
    id: bigint;
    customerName: string;
    status: string;
    serviceName: string;
    date: string;
    notes: string;
    quantity: bigint;
    customerId?: bigint;
    serviceId: string;
    phone: string;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        serviceName: value.serviceName,
        date: value.date,
        notes: value.notes,
        quantity: value.quantity,
        customerId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.customerId)),
        serviceId: value.serviceId,
        phone: value.phone,
        totalPrice: value.totalPrice
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    cnic: string;
    designation: string;
    fullName: string;
    fatherName: string;
    bloodGroup: string;
    mobile: string;
    photo: _ExternalBlob;
}): Promise<{
    id: bigint;
    age: bigint;
    cnic: string;
    designation: string;
    fullName: string;
    fatherName: string;
    bloodGroup: string;
    mobile: string;
    photo: ExternalBlob;
}> {
    return {
        id: value.id,
        age: value.age,
        cnic: value.cnic,
        designation: value.designation,
        fullName: value.fullName,
        fatherName: value.fatherName,
        bloodGroup: value.bloodGroup,
        mobile: value.mobile,
        photo: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.photo)
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inStock: boolean;
    icon: string;
    name: string;
    description: string;
    discount: bigint;
    image: _ExternalBlob;
    price: string;
}): Promise<{
    id: bigint;
    inStock: boolean;
    icon: string;
    name: string;
    description: string;
    discount: bigint;
    image: ExternalBlob;
    price: string;
}> {
    return {
        id: value.id,
        inStock: value.inStock,
        icon: value.icon,
        name: value.name,
        description: value.description,
        discount: value.discount,
        image: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerOrder>): Array<CustomerOrder> {
    return value.map((x)=>from_candid_CustomerOrder_n17(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Promise<Array<Employee>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Employee_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Promise<Array<Service>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Service_n24(_uploadFile, _downloadFile, x)));
}
function to_candid_CustomerOrder_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerOrder): _CustomerOrder {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_Employee_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): Promise<_Employee> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Service_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): Promise<_Service> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    cnic: string;
    designation: string;
    fullName: string;
    fatherName: string;
    bloodGroup: string;
    mobile: string;
    photo: ExternalBlob;
}): Promise<{
    id: bigint;
    age: bigint;
    cnic: string;
    designation: string;
    fullName: string;
    fatherName: string;
    bloodGroup: string;
    mobile: string;
    photo: _ExternalBlob;
}> {
    return {
        id: value.id,
        age: value.age,
        cnic: value.cnic,
        designation: value.designation,
        fullName: value.fullName,
        fatherName: value.fatherName,
        bloodGroup: value.bloodGroup,
        mobile: value.mobile,
        photo: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.photo)
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inStock: boolean;
    icon: string;
    name: string;
    description: string;
    discount: bigint;
    image: ExternalBlob;
    price: string;
}): Promise<{
    id: bigint;
    inStock: boolean;
    icon: string;
    name: string;
    description: string;
    discount: bigint;
    image: _ExternalBlob;
    price: string;
}> {
    return {
        id: value.id,
        inStock: value.inStock,
        icon: value.icon,
        name: value.name,
        description: value.description,
        discount: value.discount,
        image: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: string;
    serviceName: string;
    date: string;
    notes: string;
    quantity: bigint;
    customerId?: bigint;
    serviceId: string;
    phone: string;
    totalPrice: bigint;
}): {
    id: bigint;
    customerName: string;
    status: string;
    serviceName: string;
    date: string;
    notes: string;
    quantity: bigint;
    customerId: [] | [bigint];
    serviceId: string;
    phone: string;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        serviceName: value.serviceName,
        date: value.date,
        notes: value.notes,
        quantity: value.quantity,
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        serviceId: value.serviceId,
        phone: value.phone,
        totalPrice: value.totalPrice
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
